### ISSUE TITLE
These scripts are deprecated.  Use curator instead.

### ISSUE THREAD

**Issue by untergeek** [crashdump/logstash-elasticsearch-scripts#3]
I wrote the original logstash_index_cleaner.py script (see https://logstash.jira.com/browse/LOGSTASH-211).  It's been superseded by [curator](https://github.com/elasticsearch/curator) which is officially supported by Elasticsearch (see http://www.elasticsearch.org/blog/curator-tending-your-time-series-indices/) and uses the official Elasticsearch python module.  It's been updated to use the Elasticsearch 1.0 API (though no PyPI release for this version has been made yet) but maintains a branch `0.6` for continued use by versions of Elasticsearch < `1.0`.

If you're installing for Elasticsearch versions 0.90.12 or older:

```
pip install elasticsearch==0.4.4
pip install elasticsearch-curator
```

**Comment by crashdump** [comment]
It took me 7 years, but I finaly updated the readme to reflect this. Thanks!
